import { getArticle } from "@/utils/content/getArticle";
import { getArticles } from "@/utils/content/getArticles";

export const generateOGImageUrl = (path: string) =>
  path.toLowerCase().replace(/^\//, "").replace(/\/$/, "") + ".png";

/**
 * Get the path to the OpenGraph image for a page
 * @param path Pathname of the page URL.
 * @returns Path to the OpenGraph image if found. Otherwise, `undefined`.
 */
export async function getOgImageUrl(path: string): Promise<string | undefined> {
  /**  All the OpenGraph image paths as generated by our `getStaticPaths`. */
  const articles = await getArticles();
  const paths = new Set(articles.map((article) => `${article.slug}.png`));
  let imagePath = generateOGImageUrl(path);
  console.log(paths, path, imagePath);
  if (paths.has(imagePath)) return "/open-graph/" + imagePath;
}
