import type { GetStaticPathsOptions, GetStaticPathsResult } from "astro";
import {
  generateOGImageUrl,
  getStaticPaths,
} from "../pages/open-graph/[...route]";

const routes = (await getStaticPaths(
  {} as GetStaticPathsOptions
)) as GetStaticPathsResult;

/**  All the OpenGraph image paths as generated by our `getStaticPaths`. */
const paths = new Set(routes.map(({ params }) => params.route));

/**
 * Get the path to the OpenGraph image for a page
 * @param path Pathname of the page URL.
 * @returns Path to the OpenGraph image if found. Otherwise, `undefined`.
 */
export function getOgImageUrl(path: string): string | undefined {
  let imagePath = generateOGImageUrl(path);
  console.log("imagepath:", imagePath);
  console.log(paths.has(imagePath));
  if (paths.has(imagePath)) return "/open-graph/" + imagePath;
}
