name: daily-build

on:
  schedule:
    - cron: "1 13 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: daily_build

    steps:
      - name: trigger netlify build
        shell: bash
        env:
          BUILD_HOOK: ${{ secrets.BUILD_HOOK_ID }}
        run: |
          curl -X POST -d '{}' "https://api.netlify.com/build_hooks/$BUILD_HOOK_ID"
