name: daily-build

on:
  schedule:
    - cron: "1 13 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: trigger netlify build
        run: |
          curl -X POST -d '{}' "https://api.netlify.com/build_hooks/64904f02b32a795fdc466a59"
